logging:
  level:
    ROOT: INFO
    com.wanafiq.ecdsa: DEBUG

spring:
  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    name: ekyc
    url: jdbc:h2:mem:ecdsa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true