logging:
  level:
    ROOT: INFO
    com.wanafiq.ecdsa: DEBUG

spring:
  datasource:
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    name: ekyc
    url: jdbc:h2:mem:ecdsa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  h2:
    console:
      enabled: true
      path: /h2

application:
  jwt:
    private-key: |
      -----BEGIN PRIVATE KEY-----
      
      -----END PRIVATE KEY-----
    public-key: |
      -----BEGIN PUBLIC KEY-----
      
      -----END PUBLIC KEY-----
    issuer: https://localhost:8081
    expiryInHours: 24
  cors:
    allowed-origins:
      - http://localhost:3000